version: '3.8'

services:
  # ===========================
  # Base de datos PostgreSQL
  # ===========================
  postgres:
    image: postgres:16
    container_name: vac-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vacdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vac-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # ===========================
  # Backend (NestJS)
  # ===========================
  backend:
    build:
      context: ./VacationBackend
      dockerfile: Dockerfile
    container_name: vac-backend
    restart: unless-stopped
    environment:
      DATABASE_TYPE: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      DATABASE_NAME: vacdatabase
      BACKEND_PORT: 3010
      FRONTEND_HOST: "*"
      JWT_SECRET: tu_clave_super_secreta
      JWT_EXPIRES_IN: 2d
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3010:3010"
    networks:
      - vac-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3010/health || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 60s

  # ===========================
  # Frontend (Next.js)
  # ===========================
  frontend:
    build:
      context: ./vacationsFrontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL=http://192.168.1.16:3010
    container_name: vac-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=4001
      - NEXT_PUBLIC_API_BASE_URL=http://192.168.1.16:3010
    depends_on:
      - backend
    ports:
      - "4001:4001"
    networks:
      - vac-network

volumes:
  postgres_data:

networks:
  vac-network:
    driver: bridge
