version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: vac-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: vacdatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vac-network

  backend:
    build:
      context: ./VacationBackend  # ✅ Cambiar contexto
      dockerfile: Dockerfile
    container_name: vac-backend
    environment:
      DATABASE_TYPE: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
      DATABASE_NAME: vacdatabase
      BACKEND_PORT: 3010
      FRONTEND_HOST: http://192.168.1.16:4001
      JWT_SECRET: tu_clave_super_secreta
      JWT_EXPIRES_IN: 2d
      USE_MOCK: false
      API_BASE_URL: http://localhost:1337/api/personas
    depends_on:
      - postgres
    ports:
      - "3010:3010"
    networks:
      - vac-network

  frontend:
    build:
      context: ./vacationsFrontend  # ✅ Agregar frontend
      dockerfile: Dockerfile
    container_name: vac-frontend
    environment:
      - PORT=4001
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3010
      - NODE_ENV=production
    depends_on:
      - backend
    ports:
      - "4001:4001"
    networks:
      - vac-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  vac-network:
    driver: bridge