version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: vac-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vacaciones_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vac-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vac-backend
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: vacaciones_db
      BACKEND_PORT: 3010  # ✅ Cambiado a 3010
      FRONTEND_HOST: http://localhost:4001
    depends_on:
      - postgres
    ports:
      - "3010:3010"  # ✅ Cambiado a 3010
    networks:
      - vac-network

volumes:
  postgres_data:

networks:
  vac-network:
    driver: bridge